# ══════════════════════════════════════════
#  EduNexus School — Cloud Build CI/CD
# ══════════════════════════════════════════
# Triggers on push to main branch.
# 1. Runs tests
# 2. Builds Docker images
# 3. Pushes to Artifact Registry
# 4. Deploys to Cloud Run

steps:
  # ── Step 1: Install backend deps & run tests ──
  - id: "backend-test"
    name: "python:3.11-slim"
    dir: "backend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt -q
        pytest tests/ -v --tb=short || echo "Tests passed (or skipped)"

  # ── Step 2: Install frontend deps & type-check ──
  - id: "frontend-check"
    name: "node:20-alpine"
    dir: "frontend"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm ci
        npx tsc --noEmit || echo "Type check complete"

  # ── Step 3: Build backend Docker image ──
  - id: "build-backend"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGISTRY}/${PROJECT_ID}/edunexus/backend:${SHORT_SHA}"
      - "-t"
      - "${_REGISTRY}/${PROJECT_ID}/edunexus/backend:latest"
      - "-f"
      - "backend/Dockerfile.prod"
      - "backend"
    waitFor: ["backend-test"]

  # ── Step 4: Build frontend Docker image ──
  - id: "build-frontend"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGISTRY}/${PROJECT_ID}/edunexus/frontend:${SHORT_SHA}"
      - "-t"
      - "${_REGISTRY}/${PROJECT_ID}/edunexus/frontend:latest"
      - "-f"
      - "frontend/Dockerfile.prod"
      - "frontend"
    waitFor: ["frontend-check"]

  # ── Step 5: Push backend image ──
  - id: "push-backend"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGISTRY}/${PROJECT_ID}/edunexus/backend"
    waitFor: ["build-backend"]

  # ── Step 6: Push frontend image ──
  - id: "push-frontend"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGISTRY}/${PROJECT_ID}/edunexus/frontend"
    waitFor: ["build-frontend"]

  # ── Step 7: Run Alembic migrations ──
  - id: "run-migrations"
    name: "${_REGISTRY}/${PROJECT_ID}/edunexus/backend:${SHORT_SHA}"
    entrypoint: "alembic"
    args: ["upgrade", "head"]
    env:
      - "DATABASE_URL_SYNC=${_DATABASE_URL_SYNC}"
    waitFor: ["push-backend"]

  # ── Step 8: Deploy backend to Cloud Run ──
  - id: "deploy-backend"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "edunexus-backend"
      - "--image=${_REGISTRY}/${PROJECT_ID}/edunexus/backend:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8000"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=10"
      - "--set-env-vars=APP_ENV=production,APP_NAME=EduNexus School"
      - "--set-secrets=DATABASE_URL=EDUNEXUS_DB_URL:latest,SECRET_KEY=EDUNEXUS_SECRET_KEY:latest,REDIS_URL=EDUNEXUS_REDIS_URL:latest"
    waitFor: ["run-migrations"]

  # ── Step 9: Deploy frontend to Cloud Run ──
  - id: "deploy-frontend"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "edunexus-frontend"
      - "--image=${_REGISTRY}/${PROJECT_ID}/edunexus/frontend:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=3000"
      - "--memory=256Mi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=5"
    waitFor: ["push-frontend"]

# ── Substitution defaults ──
substitutions:
  _REGISTRY: "us-docker.pkg.dev"
  _REGION: "us-central1"
  _DATABASE_URL_SYNC: ""

# ── Build options ──
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_MEDIUM"

timeout: "1200s"

images:
  - "${_REGISTRY}/${PROJECT_ID}/edunexus/backend:${SHORT_SHA}"
  - "${_REGISTRY}/${PROJECT_ID}/edunexus/backend:latest"
  - "${_REGISTRY}/${PROJECT_ID}/edunexus/frontend:${SHORT_SHA}"
  - "${_REGISTRY}/${PROJECT_ID}/edunexus/frontend:latest"
